baseURL = 'https://ejacobg.com/'
languageCode = 'en-us'
title = 'Ean Jacob Gayban'
theme = 'ejacobg'
publishDir = 'docs'

[markup]
    [markup.highlight]
        noClasses = false

[params]
    mainSections = ['blog', 'notes', 'projects']